@MiniShop= http://localhost:5112

GET {{MiniShop}}/products/
Accept: application/json

###
POST {{MiniShop}}/products
Content-Type: application/json

{
  "name": "Logiciel Postgres",
  "price": 29.99
}
###
